networks:
  webshot-roulette:
    driver: bridge

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - webshot-roulette

  server:
    image: ${CLIENT_IMAGE:-ghcr.io/tonyd33/webshot-roulette/server}
    build:
      context: .
      dockerfile: server.Dockerfile
    depends_on:
      redis:
        condition: service_started
    container_name: server
    command: "node dist/server/src/main.js"
    ports:
      - "6707:6707"
    environment:
      - PORT=6707
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - webshot-roulette

  client:
    image: ${CLIENT_IMAGE:-ghcr.io/tonyd33/webshot-roulette/client}
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      server:
        condition: service_started
    container_name: client
    command: "npm run start"
    ports:
      - "9422:9422"
    environment:
      - PORT=9422
      - "SERVER_URL=http://server:6707"
    networks:
      - webshot-roulette
