import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/toaster";
import { Comic_Neue } from "next/font/google";
import "./globals.css";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const comic_neue = Comic_Neue({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-comic-neue",
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Webshot Roulette",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${comic_neue.variable} antialiased`}
      >
        {children}
        <Toaster />
      </body>
    </html>
  );
}
